-- 0005 - SSL sertifika yollari (cert + key)
ALTER TABLE domains
  ADD COLUMN IF NOT EXISTS cert_path VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS key_path VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ssl_kaynak VARCHAR(32) NOT NULL DEFAULT '';
