-- 0006 - service_plans (hizmet paketleri) + domains.plan_id
CREATE TABLE IF NOT EXISTS service_plans (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ad VARCHAR(64) NOT NULL UNIQUE,
  aciklama VARCHAR(255) NOT NULL DEFAULT '',
  disk_kota_mb INT NOT NULL DEFAULT 0,
  trafik_kota_mb INT NOT NULL DEFAULT 0,
  max_domain INT NOT NULL DEFAULT 0,
  max_db INT NOT NULL DEFAULT 0,
  max_email INT NOT NULL DEFAULT 0,
  max_ftp INT NOT NULL DEFAULT 0,
  varsayilan TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

ALTER TABLE domains
  ADD COLUMN IF NOT EXISTS plan_id BIGINT UNSIGNED NULL,
  ADD KEY IF NOT EXISTS ix_domains_plan (plan_id);
