CREATE TABLE IF NOT EXISTS firewall_kurallari (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tip VARCHAR(12) NOT NULL,
  ip VARCHAR(64) NOT NULL DEFAULT '',
  port INT NOT NULL DEFAULT 0,
  protokol VARCHAR(4) NOT NULL DEFAULT 'tcp',
  aciklama VARCHAR(200) NOT NULL DEFAULT '',
  aktif TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  KEY ix_fw_tip (tip),
  KEY ix_fw_aktif (aktif)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
