CREATE TABLE IF NOT EXISTS cp_domain_redis (
  domain_id BIGINT NOT NULL PRIMARY KEY,
  sk VARCHAR(32) NOT NULL,
  redis_pass VARCHAR(64) NOT NULL,
  aktif TINYINT NOT NULL DEFAULT 1,
  olusturulma TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
